# Generated by Django 4.2.5 on 2023-09-23 13:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('contributors', models.ManyToManyField(related_name='contributed_projects', to='users.student')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.university')),
                ('tags', models.ManyToManyField(related_name='projects', to='projects.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
